language: python
python:
    - "3.6"

install:
    - pip install pipenv
    - pipenv install --dev
    - pipenv graph

script:
    - make test

after_success:
    - pipenv run codecov --token 64da669b-222d-4a41-8747-01434fb8ad44